version: "3"

services:
  backend:
    build:
      context: ./backend
    command: air
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
      build:
        context: ./frontend
      command: yarn start
      ports:
        - 8080:8080
      volumes:
        - ./frontend:/app
        - node_modules-volume:/app/node_modules
      working_dir: /app

volumes:
  node_modules-volume:
