version: "3"

services:
  backend:
    build:
      context: ./backend
    command: air
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - node_modules-volume:/app/node_modules
    working_dir: /app

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - datavolume:/var/lib/mysql

  skeema:
    build:
      context: ./skeema
    depends_on:
      - db
    volumes:
      - ./skeema:/go/skeema

volumes:
  node_modules-volume:
  datavolume: