version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    command: air
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env.backend

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    command: yarn start
    ports:
      - 1234:1234
    volumes:
      - ./frontend:/app
      - node_modules-volume:/app/node_modules
    working_dir: /app
    env_file:
      - .env.frontend

  db:
    build:
      context: ./docker/db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    cap_add:
      - SYS_NICE
    volumes:
      - datavolume:/var/lib/mysql
      - ./db/reset.sql:/reset.sql
      - ./db/reset:/reset
      - ./docker/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  skeema:
    build:
      context: ./docker/skeema
    depends_on:
      - db
    volumes:
      - ./db:/go/db

volumes:
  node_modules-volume:
  datavolume: