FROM mysql:8.0

RUN apt-get update -y && \
    apt-get install -y locales && \
    echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=ja_JP.UTF-8

ENV LANG="ja_JP.UTF-8" \
    TZ="Asia/Tokyo"

CMD ["mysqld"]
